apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb  # This should match the labels in your Node.js Deployment
  ports:
    - protocol: TCP
      port: 27017  # Port to expose on the service
      targetPort: 27017  
  type: NodePort  # Change to NodePort or ClusterIP if needed