apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app  # This should match the labels in your Node.js Deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 3000  # Port that your Node.js app is listening on
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
