apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 3
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: alexanderson2209/tech254-alex-nodejs:v1
        ports:
        - containerPort: 3000  # Port the node.js app listens on
        env:
        - name: DB_HOST
          value: mongodb://10.108.27.134:27017/posts
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c", node seeds/seed.js]